### PR TITLE
Integrate MCC metric

### PR DESCRIPTION
**Pull request by popojargo**

### CODE REVIEW

**Review by PhilipMay — APPROVED** [review]
LGTM. Thanks!

**Comment by PhilipMay** [comment]
@popojargo I think now you should be able to Merge the PR by yourself.

**Comment by popojargo** [comment]
> @popojargo I think now you should be able to Merge the PR by yourself.

Yeah, I just wanted an approval :)

**Comment by popojargo** [comment]
@PhilipMay Any way you can publish an update soon?

**Comment by PhilipMay** [comment]
> @PhilipMay Any way you can publish an update soon?

Yes sure. Tell me when please.
What about a gitter channel for this module?

**Comment by popojargo** [comment]
> > @PhilipMay Any way you can publish an update soon?
> 
> Yes sure. Tell me when please.
> What about a gitter channel for this module?

Having a more reactive platform for chat can always be better. And I'll take that new release whenever it's available haha

**Comment by PhilipMay** [comment]
It is: https://gitter.im/mlt-box
I think you can just join it.

**Pull request merged**
