### PR TITLE
[Keras] Allow to provide custom metric

### PR DESCRIPTION
**Pull request by popojargo**
This PR makes the metrics of the callback parametric. 

The default metrics are kept as it is. I'm unsure if we want to keep the `best_f1` or if I should just convert it to a DefaultMetric function?

Updated documentation and tested with the example

### CODE REVIEW

**Comment by popojargo** [comment]
I also want to add the MCC coefficient. I'll land a PR if this one is accepted. You can see how easily we can add default metrics: https://github.com/popojargo/mltb/commit/00aca6ae1acda8be6fefeadfb4838a3be04b3b57

**Comment by PhilipMay** [comment]
Thanks. :-)
Nice job. 

What about giving cou commit rights for this project? Are you interested?

**Comment by popojargo** [comment]
Sure thing! I've also done some work around hyperopt. I've made little wrapper that saves checkpoints after every X steps. I could look with you how we can integrate that with your existing work.

**Comment by PhilipMay** [comment]
> Sure thing! I've also done some work around hyperopt. I've made little wrapper that saves checkpoints after every X steps. I could look with you how we can integrate that with your existing work.

Yes sure. Great!
I stopped working on hyperopt to be honest. I discovered optuna which imo is way better.

**Pull request merged**
